#CI项目名
name: Mediatek-lede

on:
  #自动编译：每天早上4点
  schedule:
    - cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  openwrt_config:
    #调用公用编译核心openWRT-CORE.yml
    uses: ./.github/workflows/openWRT-CORE.yml
    with:
      #编译平台
      openWRT_TARGET: Mediatek
      #默认主题
      openWRT_THEME: argon
      #默认主机名
      openWRT_NAME: openWRT
      #默认密码，仅作展示，请勿乱改
      openWRT_PW: 无
      #默认地址
      openWRT_IP: 192.168.2.1
      #默认源码
      openWRT_URL: https://github.com/abandon-xyz/lede.git
      
