#云编译公用核心
name: openWRT-CORE

on:
  #公用核心标识
  workflow_call:
    inputs:
      openWRT_TARGET:
        required: true
        type: string
      openWRT_THEME:
        required: true
        type: string
      openWRT_NAME:
        required: true
        type: string
      openWRT_URL:
        required: true
        type: string
      openWRT_BRANCH:
        required: false
        type: string
      openWRT_PW:
        required: true
        type: string
      openWRT_IP:
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  openWRT_TARGET: ${{inputs.openWRT_TARGET}}
  openWRT_THEME: ${{inputs.openWRT_THEME}}
  openWRT_NAME: ${{inputs.openWRT_NAME}}
  openWRT_URL: ${{inputs.openWRT_URL}}
  openWRT_BRANCH: ${{inputs.openWRT_BRANCH}}
  openWRT_PW: ${{inputs.openWRT_PW}}
  openWRT_IP: ${{inputs.openWRT_IP}}

jobs:
  openwrt_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E rm -rf $(cat $GITHUB_WORKSPACE/Depends.txt | sed -n "1{s/\r$//;p;q}")
          sudo -E apt -yqq update
          sudo -E apt -yqq purge $(cat $GITHUB_WORKSPACE/Depends.txt | sed -n "2{s/\r$//;p;q}")
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq install $(cat $GITHUB_WORKSPACE/Depends.txt | sed -n "3{s/\r$//;p;q}")
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Initialization Values
        run: |
          export openWRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          export openWRT_SOURCE=$(echo $openWRT_URL | cut -d '/' -f 5)
          export openWRT_TYPE=$(sed -n "1{s/^#//;s/\r$//;p;q}" $GITHUB_WORKSPACE/Config/$openWRT_TARGET.txt)

          echo "openWRT_SOURCE=$openWRT_SOURCE" >> $GITHUB_ENV
          echo "openWRT_TARGET=$openWRT_TARGET" >> $GITHUB_ENV
          echo "openWRT_DATE=$openWRT_DATE" >> $GITHUB_ENV
          echo "openWRT_TYPE=$openWRT_TYPE" >> $GITHUB_ENV
          echo "openWRT_PW=$openWRT_PW" >> $GITHUB_ENV
          echo "openWRT_IP=$openWRT_IP" >> $GITHUB_ENV

      - name: Check Scripts
        run: |
          cd ./Scripts

          chmod +x ./*.sh
          dos2unix ./*.sh

      - name: Clone openWRT Code
        run: |
          git clone --depth=1 --single-branch --branch $openWRT_BRANCH $openWRT_URL ./openwrt

      - name: Update Feeds
        run: |
          cd ./openwrt

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom Scripts
        run: |
          cd ./openwrt

          $GITHUB_WORKSPACE/Scripts/Settings.sh

          cd ./package

          $GITHUB_WORKSPACE/Scripts/Plugins.sh

      - name: Custom Settings
        run: |
          cd ./openwrt

          rm -rf ./tmp* ./.config*
          cat $GITHUB_WORKSPACE/Config/$openWRT_TARGET.txt $GITHUB_WORKSPACE/Config/General.txt >> .config

          $GITHUB_WORKSPACE/Scripts/Extras.sh

          make defconfig

      - name: Cleanup Toolchain
        run: |
          cd ./openwrt

          make dirclean

      - name: Download Packages
        run: |
          cd ./openwrt

          make download -j$(nproc)

      - name: Compile Firmware
        run: |
          cd ./openwrt

          make -j$(nproc) || make -j1 V=s

          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1
          echo "======================="

      - name: Package Firmware
        run: |
          cd ./openwrt && mkdir ./upload

          rm -rf $(find ./bin/targets/ -iregex ".*\(json\|manifest\|buildinfo\|sha256sums\|packages\)$")
          cp -rf $(find ./bin/targets/ -type f -iname "*.*") ./upload/
          cp -rf ./.config ./upload/Config_"$openWRT_TARGET"_"$openWRT_SOURCE"_"$openWRT_DATE".txt

          cd ./upload

          $GITHUB_WORKSPACE/Scripts/Renames.sh

      - name: Release Firmware
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{env.openWRT_TARGET}}_${{env.openWRT_SOURCE}}_${{env.openWRT_DATE}}
          files: ./openwrt/upload/*.*
          body: |
            wr30u固件
            
            源码地址: ${{env.openWRT_URL}}
            源码：${{env.openWRT_SOURCE}}
            平台：${{env.openWRT_TARGET}}
            设备：${{env.openWRT_TYPE}}
            密码：${{env.openWRT_PW}}
            地址：${{env.openWRT_IP}}

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 5
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
